### ISSUE TITLE
reduce the number of requests

### ISSUE THREAD

**Issue by Lengso** [projectdiscovery/uncover#12]
According to the [**uncover** document](https://github.com/projectdiscovery/uncover/blob/main/README.md#running-uncover), you can search for multiple dorks
 
My idea is to read multiple statements in the dork.txt file, which can be combined together, and one request can get the return results of all statements

dork.txt
```
ssl:"Uber Technologies, Inc."
title:"Grafana"
```

For example, all engines support `|| or` flag
```
fofa :  ssl:"Uber Technologies, Inc." || title:"Grafana"
censys : ip="1.1.1.1" or  ip="1.1.1.1"
```

_Originally posted by @Lengso in https://github.com/projectdiscovery/uncover/discussions/10_

**Comment by ehsandeep** [comment]
Closing as of now, as it is still being discussed here - https://github.com/projectdiscovery/uncover/discussions/10 and we in the current form we can specify multiple queries as part of single query if supported by the engine.
