### ISSUE TITLE
Parsing issue with IP/CIDR input as query

### ISSUE THREAD

**Issue by mxrch** [projectdiscovery/uncover#121]
Hi !

I saw that CIDR targets are only being searched on shodan/shodan-idb, but you can also use CIDR on Censys Search (ex : https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=51.91.110.0%2F24)

I didn't managed to make a PR for it, but I think it could be a useful feature ? 😄

**Comment by ehsandeep** [comment]
Looks like you found a bug @mxrch in the code; it's something should be supported, as any input can be passed as part of the query, but for some parsing issues currently, it is being ignored.

```console
uncover -q "51.91.110.0/24" -e censys -v

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/ v0.0.9

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using uncover, you also agree to the terms of the APIs used.

```

**Comment by ehsandeep** [comment]
@mxrch this is now fixed with latest release - https://github.com/projectdiscovery/uncover/releases/tag/v1.0.2
