### ISSUE TITLE
quake api is not working on windows

### ISSUE THREAD

**Issue by tk-t0n0y** [projectdiscovery/uncover#144]
=> uncover.exe   -qk  'google.com'  -v     -config /provider-config.yaml

=> [[33mquake[0m] json: cannot unmarshal string into Go struct field Response.code of type int

api key is 100% correct and working

**Comment by bongobongoland** [comment]
having similar issues on kali.
some requests go through, some give an error
![image](https://user-images.githubusercontent.com/129246896/229438062-ca89a023-75ec-40af-8fd1-88716502075d.png)

**Comment by ehsandeep** [comment]
@tk-t0n0y fixed in latest release - https://github.com/projectdiscovery/uncover/releases/tag/v1.0.4
