### ISSUE TITLE
When calling FOFA API, the set field name is wrong 

### ISSUE THREAD

**Issue by TEag1e** [projectdiscovery/uncover#177]
https://github.com/projectdiscovery/uncover/blob/main/uncover/agent/fofa/fofa.go#L17

I guess you are planning to use `domain` field to represent the result domain name information, but in FOFA `domain` field represents the **primary domain name of the target.**

Example, when the result is: `api.baidu.com`, then `domain` value of the field is `baidu.com`. If a user wants to query all Baidu domain names in FOFA, your way of writing will only return one record `baidu.com`.

![图片](https://user-images.githubusercontent.com/34545908/225859031-458a46f4-661b-459a-8c4b-3f300768e379.png)

![图片](https://user-images.githubusercontent.com/34545908/225860089-f08c0474-2d95-4028-896a-d027fd7e912f.png)

You should use the `host` field in the FOFA API to represent domain information.

**Comment by ehsandeep** [comment]
@TEag1e fixed with https://github.com/projectdiscovery/uncover/releases/tag/v1.0.4
