### ISSUE TITLE
SHODAN_API_KEY_2 is used as a key

### ISSUE THREAD

**Issue by bongobongoland** [projectdiscovery/uncover#188]
Took me some time to figure out why shodan module wasn't working... So I added API key 1 because I only have one key, but I did not delete `- SHODAN_API_KEY_2` from provider-config.yaml
For some reason, uncover decided not to use the real key and just kept trying to use `SHODAN_API_KEY_2` as a key. Once I removed
`- SHODAN_API_KEY_2` everything started working fine.

**Comment by ehsandeep** [comment]
See https://github.com/projectdiscovery/uncover#provider-configuration, you need to ensure you are not adding invalid keys to config file as they not validated and used as it is.

> When multiple keys/credentials are specified for same provider in the config file, random key will be used for each execution.
