### ISSUE TITLE
-o doesn't work in 1.0.4

### ISSUE THREAD

**Issue by bongobongoland** [projectdiscovery/uncover#214]
I can see the results in the terminal, however, the output is not saved and there's no output file at all.

**Comment by ehsandeep** [comment]
regession of https://github.com/projectdiscovery/uncover/issues/84

**Comment by AeonDave** [comment]
also -j or -r. i see the output as a list of ips. if i put -j or -r at the beginning of the args, there is no output

**Comment by ehsandeep** [comment]
Fixed in latest release - https://github.com/projectdiscovery/uncover/releases/tag/v1.0.5
