### ISSUE TITLE
`-r` and `-j` option is is not working on default run

### ISSUE THREAD

**Issue by AeonDave** [projectdiscovery/uncover#231]
### uncover version:
v1.0.5 (latest)

### Current Behavior:
When running the command 'uncover.exe -r -q "any query"' in the latest version (v1.0.5), I encounter a problem.

### Expected Behavior:
I expected the command to execute and provide the desired output.

### Steps To Reproduce:
1. Run 'uncover.exe -r -q "any query"' command.

### Anything else:
I have noticed that the latest version (v1.0.5) don't produce any output with -j and -r flags
without -r or -j it works normally. but i need json for scripting.

```
uncover.exe -r -q element

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /
\__,_/_/ /_/\___/\____/|___/\___/_/

                projectdiscovery.io

[INF] Current uncover version v1.0.5 (latest)

uncover.exe -j -q element

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /
\__,_/_/ /_/\___/\____/|___/\___/_/

                projectdiscovery.io

[INF] Current uncover version v1.0.5 (latest)
```

with 1.0.3

```
uncover.exe -r -q element

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /
\__,_/_/ /_/\___/\____/|___/\___/_/

                projectdiscovery.io

[INF] Current uncover version v1.0.3 (outdated)
{"_shodan":{"crawler": .....
```

**Comment by MetzinAround** [comment]
Thanks for the issue @AeonDave. I'm working on recreating this right now. In the meantime I'll tag @ehsandeep for some help in case he's seen this before.

**Comment by ehsandeep** [comment]
@AeonDave looks like both options are working with `-v` option and not in default mode, which is not expected and needs to be fixed.

**Comment by ehsandeep** [comment]
@AeonDave I was sharing about the current behavior with bug. Indeed we are fixing the issue here - https://github.com/projectdiscovery/uncover/pull/235, reopening the issue to tag with release.
