### ISSUE TITLE
It finds less results without the `-s` flag

### ISSUE THREAD

**Issue by Firpo7** [projectdiscovery/uncover#300]
### uncover version:
`[INF] Current Version: v1.0.6`

### Current Behavior:
I currently have only put a shodan api key within the `provider-config.yml`, leaving the other fields empty.
When I try to run `uncover`, without specifying the engine, the command is pretty fast and does print me only few results compared to the same command but with the `-s` specified.

Here is an example:

````
user@doom:~/tests/proj$ uncover -silent -q "hotdog" | wc -l
52
user@doom:~/tests/proj$ uncover -silent -s -q "hotdog" | wc -l
400
```

### Expected Behavior:
I would expect the same number of results on both commands.

**Comment by dogancanbakir** [comment]
The flag `-s`is a shortened version of `--shodan`, and it is defined as StringSliceVarP. This means it expects one or more string arguments. If you use the `-s` flag without providing a subsequent argument, as in the first command, it may try to consume the following flag `-q` as its argument. This can lead to the behavior you described.

Try this:
```console
$ uncover -silent -q "hotdog" -s

flag needs an argument: -s
exit status 2
```

See https://github.com/projectdiscovery/uncover#running-uncover section for examples.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if you have any questions.
