### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by r0x5r** [projectdiscovery/uncover#320]
─[parrot@parrot]─[~]
└──╼ $go install -v github.com/projectdiscovery/uncover/cmd/uncover@latest
go/pkg/mod/github.com/refraction-networking/utls@v1.5.4/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.19/src/crypto/ec

**Comment by MetzinAround** [comment]
HI @rohit0x5 , It looks like you need to update to the latest version of Go. https://gist.github.com/nikhita/432436d570b89cab172dcf2894465753

**Comment by muslimfrompk** [comment]
Yes it was giving me same error but when I reinstalled(Updated) to go version 1.20 it worked

**Comment by ehsandeep** [comment]
this is an issue due to use of outdated version of go, you need to have go 1.21 to install uncover.
