### ISSUE TITLE
Add support for retries

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/uncover#47]
### Please describe your feature request:

**A server timeout may result in Shodan returning no results for a query**. There should be an argument `-retries int` similar to httpx to retry the query if the response is unexpected and the default value set to 1.

CLI flag to add:

```yaml
   -retries int                number of times to retry a failed request (default 1)
```

**Comment by LuitelSamikshya** [comment]
The test case implementation for this feature depends on https://github.com/projectdiscovery/scanme/issues/5
