### ISSUE TITLE
Google search bug

### ISSUE THREAD

**Issue by Tripse** [projectdiscovery/uncover#491]
### bug
I found some small bugs while testing new features.
This way, it can work normally.
```bash
uncover -google "site:*.hackerone.com"
```
but this way, it can not work normally
```bash
uncover -google -q "site:*.hackeron.com"
```
### uncover version
<img width="960" alt="image" src="https://github.com/projectdiscovery/uncover/assets/110890002/52c9981b-dbd9-4493-8bce-8ecaeb2f9e8e">

**Comment by Tripse** [comment]
Here is my hilarious testing process
https://github.com/projectdiscovery/uncover/discussions/490

**Comment by dogancanbakir** [comment]
You need to provide an argument for the flag you're using, as you did in the first command. In the second command, you don't provide an argument for the `-google` flag.
