### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by c4ir0** [projectdiscovery/uncover#79]
the` /home/kali/.config/uncover/` dir doesn't exist to make the .yaml file 

should I create one, will this work !!

![Capture](https://user-images.githubusercontent.com/108268587/190880158-0cb4e24e-8401-4b55-bed6-132396431d40.JPG)

**Comment by Nikakz** [comment]
Resolveu?

**Comment by ehsandeep** [comment]
@c4ir0 Yes, you can create provider config file as shared - https://github.com/projectdiscovery/uncover#provider-configuration
