### ISSUE TITLE
Censys - Add option to include include Virtual Hosts

### ISSUE THREAD

**Issue by Techbrunch** [projectdiscovery/uncover#81]
Currently the Censys agent exclude all [Virtual Hosts](https://support.censys.io/hc/en-us/articles/4411773845524-Introduction-to-Virtual-Hosts): 

https://github.com/projectdiscovery/uncover/blob/b0993e24d16fa496ce7870f0d41e2d7f2842c893/uncover/agent/censys/censys.go#L15

I think those should be included or there should be an option to include them if needed.

This won't return any results:

```
echo 'name: "*.arvala7.space" or name: "*.kintan.space"' | uncover -e censys -v
```

but the [same query on Censys](https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=INCLUDE&q=name%3A%22*.arvala7.space%22+or+name%3A%22*.kintan.space%22) with Virtual Hosts included will return 7 results.

**Comment by ehsandeep** [comment]
@Techbrunch, thanks for pointing this out; this is now updated in dev version to include virtual hosts - https://github.com/projectdiscovery/uncover/pull/82
